export const appConstants = {
  WAIT: 'APP_LOADING',
  SUCCESS: 'LOAD_SUCCESSFULLY',
  ERROR: 'LOAD_WITH_ERROR',
  SET_COURSE: 'SET_CURRENT_COURSE',
  SET_FILTER_SEARCH_TEXT: 'SET_FILTER_SEARCH_TEXT',
  SET_FILTER_TAG: 'SET_FILTER_TAG',
  SET_FILTER_NEW: 'SET_FILTER_NEW',
  SET_FILTER_LEARNING: 'SET_FILTER_LEARNING',
};