export const courseConstants = {
  GET_ALL: 'GET_ALL_COURSES',
  GET_CURRENT: 'GET_CURRENT_COURSE',
  GET_INFO: 'GET_CURRENT_MODULE',
  UPDATE_MODULE: 'UPDATE_MODULE_PROGRESS',
  REVISION: 'GET_REVISION_MODULES',
};